name: Byz Tycoon Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Sync WebGL Build to DigitalOcean
      env:
        SSH_PRIVATE_KEY: ${{ secrets.IP }}
        DROPLET_IP: ${{ secrets.PASS }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
        rsync -avz --delete ./Build/ root@$DROPLET_IP:/var/www/html/